// Trim the acorn body to its silhouette, encode it compactly, and embed it in src/assets/body.ts.
// Embedding (instead of a URL) lets every context load it the same way: extension pages,
// content scripts on job sites, workers, and the demo.
// Run: bun run --cwd acorn/packages/acorn-face art:prepare
import { join } from "node:path";
import sharp from "sharp";

const ROOT = join(import.meta.dir, "..");
const SRC = join(ROOT, "art", "acorn-body.png");
const OUT = join(ROOT, "src", "assets", "body.ts");
/** Tallest the body is drawn at full detail: the 148px Help face (body ≈ 60%) at 3× density, rounded up. */
const MAX_HEIGHT = 512;
const ENCODERS = {
  webp: (img: sharp.Sharp) =>
    img.webp({ quality: 88, alphaQuality: 100, effort: 6, smartSubsample: true }),
  avif: (img: sharp.Sharp) => img.avif({ quality: 62, effort: 9, chromaSubsampling: "4:4:4" }),
} as const;

const base = sharp(SRC)
  .trim({ threshold: 0 })
  .resize({ height: MAX_HEIGHT, withoutEnlargement: true, kernel: "lanczos3" });

const results = await Promise.all(
  Object.entries(ENCODERS).map(async ([format, encode]) => {
    const { data, info } = await encode(base.clone()).toBuffer({ resolveWithObject: true });
    return { format, data, width: info.width, height: info.height };
  }),
);
for (const r of results)
  console.log(`${r.format}: ${r.width}×${r.height}, ${(r.data.length / 1024).toFixed(1)} KB`);
const best = results.reduce((a, b) => (b.data.length < a.data.length ? b : a));

await Bun.write(
  OUT,
  `// Generated by tools/prepare-art.ts from art/acorn-body.png. Do not edit.\n` +
    `export const BODY_MIME = "image/${best.format}";\n` +
    `export const BODY_WIDTH = ${best.width};\n` +
    `export const BODY_HEIGHT = ${best.height};\n` +
    `export const BODY_BASE64 =\n  "${best.data.toString("base64")}";\n`,
);
console.log(
  `Embedded ${best.format} (${(best.data.length / 1024).toFixed(1)} KB) in src/assets/body.ts`,
);
