import type { CompanyProfile, Job, Pay } from "./types";

const USD = "USD";

function yearly(min: number, max: number): Pay {
  return { min, max, currency: USD, period: "year" };
}

function hourly(min: number, max: number): Pay {
  return { min, max, currency: USD, period: "hour" };
}

export const COMPANIES: CompanyProfile[] = [
  {
    slug: "northwind",
    name: "Northwind",
    locations: "Chicago · New York",
    about: "A product studio hiring designers and analysts for in-house teams.",
    industry: "Product studio",
    size: "201–500",
    founded: 2014,
    replyDays: 3,
  },
  {
    slug: "harbor",
    name: "Harbor",
    locations: "Remote",
    about:
      "Infrastructure software. Most roles are remote, with visa support on senior engineering.",
    industry: "Developer tools",
    size: "51–200",
    founded: 2018,
    replyDays: 5,
  },
  {
    slug: "lumen",
    name: "Lumen Health",
    locations: "Austin · Seattle",
    about: "A clinic network hiring operators and engineering managers.",
    industry: "Healthcare",
    size: "1,001–5,000",
    founded: 2011,
    replyDays: 7,
  },
  {
    slug: "fieldnote",
    name: "Fieldnote",
    locations: "Remote",
    about: "A small brand studio. Some roles are shared by scouts before they hit the big boards.",
    industry: "Brand and content",
    size: "11–50",
    founded: 2020,
    replyDays: 4,
  },
  {
    slug: "beacon",
    name: "Beacon",
    locations: "New York · Remote",
    about:
      "Payroll and benefits for small teams. Design and research sit inside every product squad.",
    industry: "Fintech",
    size: "201–500",
    founded: 2016,
    replyDays: 2,
  },
  {
    slug: "atlas",
    name: "Atlas Labs",
    locations: "San Francisco · Chicago",
    about: "Applied AI for logistics. A research-heavy team that ships weekly to large carriers.",
    industry: "AI and logistics",
    size: "51–200",
    founded: 2021,
    replyDays: 6,
  },
];

export const JOBS: Job[] = [
  {
    id: "product-designer-northwind",
    title: "Product Designer",
    company: "Northwind",
    companyId: "northwind",
    location: "Chicago, IL",
    workplace: "hybrid",
    pay: yearly(140_000, 170_000),
    seniority: "Senior",
    employment: "full-time",
    postedHoursAgo: 46,
    source: "direct",
    visa: false,
    applicants: 18,
    team: "Hiring product · 9 people",
    skills: [
      "Product strategy",
      "Prototyping",
      "User research",
      "Figma",
      "Design systems",
      "Interaction design",
    ],
    summary:
      "Own the hiring product from search through interview scheduling. You will pair with research and write the interface yourself.",
    responsibilities: [
      "Lead design for search, saved jobs, and interview scheduling",
      "Run weekly sessions with job hunters and recruiters",
      "Ship production-ready specs with engineering, not just mocks",
    ],
    requirements: [
      "5+ years in product design",
      "A portfolio of complex tools",
      "Comfortable with weekly research",
    ],
    benefits: [
      "Health, dental, vision",
      "Four-day summer weeks",
      "$2,000 learning budget",
      "401(k) match",
    ],
  },
  {
    id: "frontend-engineer-harbor",
    title: "Frontend Engineer",
    company: "Harbor",
    companyId: "harbor",
    location: "Remote — United States",
    workplace: "remote",
    pay: yearly(160_000, 190_000),
    seniority: "Senior",
    employment: "full-time",
    postedHoursAgo: 22,
    source: "aggregated",
    visa: true,
    applicants: 64,
    team: "App platform · 12 people",
    skills: ["React", "TypeScript", "Accessibility", "Design systems"],
    summary:
      "Build the logged-in app: search, lists, and the interview calendar. The stack is React and a small design system.",
    responsibilities: [
      "Own the search and list surfaces end to end",
      "Grow the shared component library with design",
      "Keep the app fast on low-end devices",
    ],
    requirements: [
      "Strong React and TypeScript",
      "Care for accessible UI",
      "Visa sponsorship available",
    ],
    benefits: ["Remote stipend", "Equity", "Health coverage", "Annual team offsite"],
  },
  {
    id: "recruiter-lumen",
    title: "Technical Recruiter",
    company: "Lumen Health",
    companyId: "lumen",
    location: "Austin, TX",
    workplace: "onsite",
    pay: yearly(90_000, 110_000),
    seniority: "Mid",
    employment: "full-time",
    postedHoursAgo: 118,
    source: "direct",
    visa: false,
    applicants: 31,
    team: "Talent · 6 people",
    skills: ["Recruiting", "Sourcing", "Stakeholder management"],
    summary:
      "Run full-cycle hiring for clinical engineering. You will schedule on the platform and pay only when an interview happens.",
    responsibilities: [
      "Partner with engineering leads on role scoping",
      "Own sourcing, screens, and offers for 8–10 open roles",
      "Report weekly on pipeline health",
    ],
    requirements: [
      "3+ years recruiting engineers",
      "On-site in Austin three days a week",
      "Clear writing",
    ],
    benefits: ["Health, dental, vision", "Relocation support", "Commuter benefits"],
  },
  {
    id: "brand-designer-fieldnote",
    title: "Brand Designer",
    company: "Fieldnote",
    companyId: "fieldnote",
    location: "Remote",
    workplace: "remote",
    pay: hourly(80, 100),
    seniority: "Mid",
    employment: "contract",
    postedHoursAgo: 70,
    source: "scouted",
    visa: false,
    applicants: 6,
    team: "Studio · 4 people",
    skills: ["Brand identity", "Packaging", "Figma", "Illustration"],
    summary:
      "A three-month identity project that is not on the major boards yet. Apply through the studio’s own form.",
    responsibilities: [
      "Develop a new identity system for a food brand",
      "Design packaging for three product lines",
      "Hand off a usable brand guide",
    ],
    requirements: [
      "Identity and packaging work",
      "Available 20 hours a week",
      "Contract through June",
    ],
    benefits: ["Flexible hours", "Portfolio credit"],
  },
  {
    id: "data-analyst-northwind",
    title: "Data Analyst",
    company: "Northwind",
    companyId: "northwind",
    location: "New York, NY",
    workplace: "hybrid",
    pay: yearly(120_000, 145_000),
    seniority: "Mid",
    employment: "full-time",
    postedHoursAgo: 140,
    source: "aggregated",
    visa: false,
    applicants: 42,
    team: "Insights · 5 people",
    skills: ["SQL", "Product metrics", "Python", "Experimentation"],
    summary:
      "Measure search quality and interview rates. You will sit with design and write the definitions, not only the charts.",
    responsibilities: [
      "Define the core search and match metrics",
      "Run and read experiments with product teams",
      "Build dashboards people actually open",
    ],
    requirements: [
      "SQL and a notebook tool",
      "Experience with product metrics",
      "Hybrid in New York",
    ],
    benefits: ["Health, dental, vision", "Four-day summer weeks", "401(k) match"],
  },
  {
    id: "support-lead-harbor",
    title: "Support Lead",
    company: "Harbor",
    companyId: "harbor",
    location: "Remote",
    workplace: "remote",
    pay: yearly(75_000, 95_000),
    seniority: "Junior",
    employment: "full-time",
    postedHoursAgo: 190,
    source: "direct",
    visa: false,
    applicants: 27,
    team: "Customer experience · 8 people",
    skills: ["Customer support", "Writing", "Process design"],
    summary:
      "Lead the first response team for candidates and companies. You will write the macros and the escalation path.",
    responsibilities: [
      "Run the daily support queue",
      "Write and maintain help content",
      "Spot product issues and file them with context",
    ],
    requirements: ["2+ years in support", "Calm writing under volume", "Overlap with US hours"],
    benefits: ["Remote stipend", "Equity", "Health coverage"],
  },
  {
    id: "engineering-manager-lumen",
    title: "Engineering Manager",
    company: "Lumen Health",
    companyId: "lumen",
    location: "Seattle, WA",
    workplace: "onsite",
    pay: yearly(180_000, 210_000),
    seniority: "Lead",
    employment: "full-time",
    postedHoursAgo: 4,
    source: "scouted",
    visa: true,
    applicants: 3,
    team: "Clinic platform · 8 engineers",
    skills: ["People management", "System design", "Healthcare", "Hiring"],
    summary:
      "A hidden role for a clinic platform team of eight. The company has not posted it on LinkedIn or Indeed.",
    responsibilities: [
      "Manage and grow a team of eight engineers",
      "Own delivery for the scheduling platform",
      "Hire two senior engineers this year",
    ],
    requirements: [
      "Managed engineers before",
      "Healthcare or regulated-industry experience",
      "Seattle on-site",
    ],
    benefits: ["Health, dental, vision", "Relocation support", "Annual bonus"],
  },
  {
    id: "content-designer-fieldnote",
    title: "Content Designer",
    company: "Fieldnote",
    companyId: "fieldnote",
    location: "Remote",
    workplace: "remote",
    pay: yearly(110_000, 130_000),
    seniority: "Mid",
    employment: "full-time",
    postedHoursAgo: 288,
    source: "aggregated",
    visa: false,
    applicants: 55,
    team: "Product · 7 people",
    skills: ["UX writing", "Content strategy", "User research", "Figma"],
    summary:
      "Write the product interface and the job posts. You will work with design on empty states, errors, and search.",
    responsibilities: [
      "Own voice and tone across the product",
      "Write interface copy with designers in Figma",
      "Test language with real users",
    ],
    requirements: [
      "Product writing samples",
      "Comfort editing with designers",
      "Remote, US time zones",
    ],
    benefits: ["Flexible hours", "Health coverage", "Home office budget"],
  },
  {
    id: "senior-product-designer-beacon",
    title: "Senior Product Designer",
    company: "Beacon",
    companyId: "beacon",
    location: "Remote — United States",
    workplace: "remote",
    pay: yearly(155_000, 185_000),
    seniority: "Senior",
    employment: "full-time",
    postedHoursAgo: 9,
    source: "direct",
    visa: false,
    applicants: 12,
    team: "Payroll squad · 7 people",
    skills: [
      "Product strategy",
      "Design systems",
      "Prototyping",
      "Accessibility",
      "Figma",
      "B2B SaaS",
      "Data visualization",
    ],
    summary:
      "Redesign how small teams run payroll. You will lead design for a squad of six and own the design system’s form patterns.",
    responsibilities: [
      "Lead design for payroll runs and approvals",
      "Own form and table patterns in the design system",
      "Present work to the leadership team monthly",
    ],
    requirements: [
      "6+ years in product design",
      "Shipped complex B2B workflows",
      "Strong systems thinking",
    ],
    benefits: ["Equity", "Health, dental, vision", "Remote stipend", "Parental leave, 20 weeks"],
  },
  {
    id: "ux-researcher-beacon",
    title: "UX Researcher",
    company: "Beacon",
    companyId: "beacon",
    location: "New York, NY",
    workplace: "hybrid",
    pay: yearly(130_000, 155_000),
    seniority: "Mid",
    employment: "full-time",
    postedHoursAgo: 60,
    source: "aggregated",
    visa: true,
    applicants: 38,
    team: "Research · 4 people",
    skills: ["User research", "Survey design", "Usability testing", "Synthesis"],
    summary:
      "Run mixed-methods research for payroll and benefits. Findings go straight into squad roadmaps.",
    responsibilities: [
      "Plan and run studies across three squads",
      "Maintain the research repository",
      "Coach designers on running their own sessions",
    ],
    requirements: [
      "3+ years of UX research",
      "Qualitative and quantitative methods",
      "Hybrid in New York",
    ],
    benefits: ["Equity", "Health coverage", "Learning budget"],
  },
  {
    id: "design-systems-lead-atlas",
    title: "Design Systems Lead",
    company: "Atlas Labs",
    companyId: "atlas",
    location: "Chicago, IL",
    workplace: "hybrid",
    pay: yearly(175_000, 205_000),
    seniority: "Lead",
    employment: "full-time",
    postedHoursAgo: 30,
    source: "scouted",
    visa: false,
    applicants: 5,
    team: "Platform design · 3 people",
    skills: ["Design systems", "Accessibility", "Figma", "React", "Prototyping"],
    summary:
      "Build the first real design system for a fast-moving AI product. The role has not been posted publicly yet.",
    responsibilities: [
      "Set up tokens, components, and documentation",
      "Partner with frontend on a shared React library",
      "Mentor two product designers",
    ],
    requirements: [
      "Built or scaled a design system",
      "Comfortable reading React code",
      "Hybrid in Chicago",
    ],
    benefits: ["Equity", "Health, dental, vision", "Commuter benefits"],
  },
  {
    id: "ml-engineer-atlas",
    title: "Machine Learning Engineer",
    company: "Atlas Labs",
    companyId: "atlas",
    location: "San Francisco, CA",
    workplace: "onsite",
    pay: yearly(190_000, 240_000),
    seniority: "Senior",
    employment: "full-time",
    postedHoursAgo: 15,
    source: "aggregated",
    visa: true,
    applicants: 91,
    team: "Routing models · 10 people",
    skills: ["Python", "PyTorch", "Optimization", "System design"],
    summary: "Train and ship the routing models that plan millions of deliveries a day.",
    responsibilities: [
      "Own a model from training to production",
      "Improve evaluation and monitoring",
      "Work directly with carrier operations",
    ],
    requirements: ["4+ years in applied ML", "Production Python", "On-site in San Francisco"],
    benefits: ["Equity", "Health coverage", "Relocation support", "Daily lunch"],
  },
  {
    id: "interaction-designer-northwind",
    title: "Interaction Designer",
    company: "Northwind",
    companyId: "northwind",
    location: "Chicago, IL",
    workplace: "onsite",
    pay: hourly(70, 90),
    seniority: "Mid",
    employment: "contract",
    postedHoursAgo: 98,
    source: "direct",
    visa: false,
    applicants: 9,
    team: "Client squad · 5 people",
    skills: ["Prototyping", "Motion", "Figma", "User research"],
    summary: "A six-month contract to prototype a kiosk experience for a retail client.",
    responsibilities: [
      "Prototype touch flows and test them in store",
      "Define motion and feedback patterns",
      "Document the final flows for engineering",
    ],
    requirements: [
      "Strong prototyping portfolio",
      "On-site in Chicago",
      "Available for six months",
    ],
    benefits: ["Weekly pay", "Possible conversion to full-time"],
  },
  {
    id: "design-manager-lumen",
    title: "Design Manager",
    company: "Lumen Health",
    companyId: "lumen",
    location: "Remote — United States",
    workplace: "remote",
    pay: yearly(170_000, 195_000),
    seniority: "Lead",
    employment: "full-time",
    postedHoursAgo: 240,
    source: "direct",
    visa: false,
    applicants: 22,
    team: "Patient experience · 6 designers",
    skills: ["People management", "Product strategy", "Design systems", "User research"],
    summary: "Lead the team that designs patient scheduling and intake across 40 clinics.",
    responsibilities: [
      "Manage six product designers",
      "Set design quality bars and critique rituals",
      "Partner with product and clinical leadership",
    ],
    requirements: [
      "2+ years managing designers",
      "Healthcare experience is a plus",
      "Remote, US time zones",
    ],
    benefits: ["Health, dental, vision", "Annual bonus", "Home office budget"],
  },
  {
    id: "part-time-copywriter-fieldnote",
    title: "Copywriter",
    company: "Fieldnote",
    companyId: "fieldnote",
    location: "Remote",
    workplace: "remote",
    pay: hourly(55, 70),
    seniority: "Junior",
    employment: "part-time",
    postedHoursAgo: 36,
    source: "scouted",
    visa: false,
    applicants: 4,
    team: "Studio · 4 people",
    skills: ["Copywriting", "Brand voice", "UX writing"],
    summary: "Fifteen hours a week of campaign and website copy for studio clients.",
    responsibilities: [
      "Write launch and website copy",
      "Edit client drafts",
      "Keep the voice guide current",
    ],
    requirements: ["Published writing samples", "15 hours a week", "Remote, any US time zone"],
    benefits: ["Flexible hours", "Portfolio credit"],
  },
  {
    id: "product-analyst-beacon",
    title: "Product Analyst",
    company: "Beacon",
    companyId: "beacon",
    location: "Remote — United States",
    workplace: "remote",
    pay: yearly(115_000, 135_000),
    seniority: "Junior",
    employment: "full-time",
    postedHoursAgo: 330,
    source: "aggregated",
    visa: false,
    applicants: 76,
    team: "Growth · 6 people",
    skills: ["SQL", "Product metrics", "Experimentation"],
    summary: "Help the growth squad understand activation and retention for new payroll customers.",
    responsibilities: [
      "Own activation reporting",
      "Size and read experiments",
      "Share weekly insights",
    ],
    requirements: ["SQL fluency", "1+ year in analytics", "Clear written summaries"],
    benefits: ["Equity", "Health coverage", "Remote stipend"],
  },
];
