import { CURRENCY, DEMO_EMAIL, DEMO_PASSWORD, DEMO_USER_ID, HOLD_DAYS } from "./config";
import { addDays, isoDaysFromToday } from "./dates";
import type {
  Earning,
  Payout,
  ScoutAccount,
  ScoutNotification,
  StoreState,
  Submission,
} from "./types";

const NOW = () => new Date();

function demoAccount(): ScoutAccount {
  return {
    id: DEMO_USER_ID,
    name: "Maya Chen",
    email: DEMO_EMAIL,
    passwordText: DEMO_PASSWORD,
    phone: "+1 415 555 0142",
    emailVerified: true,
    phoneVerified: true,
    acceptedTermsAt: isoDaysFromToday(-80, NOW()),
    verificationTier: 2,
    taxInfoComplete: true,
    payoutMethod: { type: "stripe", last4: "4242" },
    level: "trusted",
    notifyDecisions: true,
    notifyRewards: true,
    createdAt: isoDaysFromToday(-90, NOW()),
  };
}

function submission(partial: Submission): Submission {
  return partial;
}

function earning(partial: Earning): Earning {
  return partial;
}

export function seedState(): StoreState {
  const scoutUserId = DEMO_USER_ID;
  const submissions: Submission[] = [
    submission({
      id: "sub-northwind",
      scoutUserId,
      jobId: "job-northwind",
      url: "https://boards.greenhouse.io/northwind/jobs/1842",
      canonicalUrl: "https://boards.greenhouse.io/northwind/jobs/1842",
      companyName: "Northwind",
      title: "Staff Platform Engineer",
      locationText: "Remote (US)",
      salaryText: "$210k–$250k",
      summary:
        "Lead matching and billing services for a hiring marketplace used by scouts and bidders.",
      tags: ["remote", "staff"],
      seniority: "senior",
      status: "approved",
      rejectionReason: "",
      autoCheckResults: [
        { id: "official", label: "Official source", outcome: "pass", detail: "Official ATS host" },
        { id: "scam", label: "Scam heuristics", outcome: "pass", detail: "Clean" },
      ],
      hiddenJob: true,
      alreadyOnMajorBoards: false,
      applications: 64,
      interviews: 5,
      hires: 1,
      submittedAt: isoDaysFromToday(-21, NOW()),
      reviewedAt: isoDaysFromToday(-21, NOW()),
      expired: false,
    }),
    submission({
      id: "sub-fieldnote",
      scoutUserId,
      jobId: "job-fieldnote",
      url: "https://jobs.lever.co/fieldnote/product-designer",
      canonicalUrl: "https://jobs.lever.co/fieldnote/product-designer",
      companyName: "Fieldnote",
      title: "Product Designer",
      locationText: "Chicago, IL",
      salaryText: "$140k–$170k",
      summary: "Design the candidate job search and company hiring workspace as one system.",
      tags: ["hybrid"],
      seniority: "mid",
      status: "approved",
      rejectionReason: "",
      autoCheckResults: [
        { id: "official", label: "Official source", outcome: "pass", detail: "Official ATS host" },
      ],
      hiddenJob: true,
      alreadyOnMajorBoards: false,
      applications: 28,
      interviews: 2,
      hires: 0,
      submittedAt: isoDaysFromToday(-9, NOW()),
      reviewedAt: isoDaysFromToday(-9, NOW()),
      expired: false,
    }),
    submission({
      id: "sub-lumen",
      scoutUserId,
      jobId: "job-lumen",
      url: "https://jobs.ashbyhq.com/lumen/rec-88",
      canonicalUrl: "https://jobs.ashbyhq.com/lumen/rec-88",
      companyName: "Lumen",
      title: "Engineering Manager",
      locationText: "New York, NY",
      salaryText: "$185k–$210k",
      summary: "Manage a team shipping interview tracking and wallet ledgers.",
      tags: ["onsite"],
      seniority: "senior",
      status: "approved",
      rejectionReason: "",
      autoCheckResults: [],
      hiddenJob: false,
      alreadyOnMajorBoards: true,
      applications: 11,
      interviews: 0,
      hires: 0,
      submittedAt: isoDaysFromToday(-4, NOW()),
      reviewedAt: isoDaysFromToday(-4, NOW()),
      expired: false,
    }),
    submission({
      id: "sub-harbor",
      scoutUserId,
      jobId: null,
      url: "https://careers.harbor.test/jobs/support-lead",
      canonicalUrl: "https://careers.harbor.test/jobs/support-lead",
      companyName: "Harbor",
      title: "Support Lead",
      locationText: "Austin, TX",
      salaryText: "",
      summary: "Own candidate support for applications that bidders and the agent submit.",
      tags: [],
      seniority: "mid",
      status: "needs_review",
      rejectionReason: "",
      autoCheckResults: [
        {
          id: "content",
          label: "Content",
          outcome: "review",
          detail: "Company domain is new — moderator should confirm it is official",
        },
      ],
      hiddenJob: true,
      alreadyOnMajorBoards: false,
      applications: 0,
      interviews: 0,
      hires: 0,
      submittedAt: isoDaysFromToday(-1, NOW()),
      reviewedAt: null,
      expired: false,
    }),
    submission({
      id: "sub-indeed",
      scoutUserId,
      jobId: null,
      url: "https://www.indeed.com/viewjob?jk=abc123",
      canonicalUrl: "https://indeed.com/viewjob",
      companyName: "Acme",
      title: "Backend Engineer",
      locationText: "Remote",
      salaryText: "",
      summary: "Build APIs for interview confirmation and scout payouts.",
      tags: [],
      seniority: "mid",
      status: "rejected",
      rejectionReason: "not an official source",
      autoCheckResults: [
        {
          id: "official",
          label: "Official source",
          outcome: "fail",
          detail: "not an official source",
        },
      ],
      hiddenJob: false,
      alreadyOnMajorBoards: false,
      applications: 0,
      interviews: 0,
      hires: 0,
      submittedAt: isoDaysFromToday(-12, NOW()),
      reviewedAt: isoDaysFromToday(-12, NOW()),
      expired: false,
    }),
    submission({
      id: "sub-dup",
      scoutUserId,
      jobId: null,
      url: "https://boards.greenhouse.io/northwind/jobs/1842",
      canonicalUrl: "https://boards.greenhouse.io/northwind/jobs/1842",
      companyName: "Northwind",
      title: "Staff Platform Engineer",
      locationText: "Remote (US)",
      salaryText: "",
      summary: "Same role, submitted after the first approved listing.",
      tags: [],
      seniority: "senior",
      status: "duplicate",
      rejectionReason: "duplicate",
      autoCheckResults: [],
      hiddenJob: false,
      alreadyOnMajorBoards: false,
      applications: 0,
      interviews: 0,
      hires: 0,
      submittedAt: isoDaysFromToday(-18, NOW()),
      reviewedAt: isoDaysFromToday(-18, NOW()),
      expired: false,
    }),
    submission({
      id: "sub-closed",
      scoutUserId,
      jobId: "job-closed",
      url: "https://jobs.lever.co/atlas/closed-role",
      canonicalUrl: "https://jobs.lever.co/atlas/closed-role",
      companyName: "Atlas",
      title: "Recruiter",
      locationText: "Remote",
      salaryText: "",
      summary: "Source candidates for complex application forms routed to human bidders.",
      tags: [],
      seniority: "entry",
      status: "approved",
      rejectionReason: "",
      autoCheckResults: [],
      hiddenJob: true,
      alreadyOnMajorBoards: false,
      applications: 7,
      interviews: 0,
      hires: 0,
      submittedAt: isoDaysFromToday(-40, NOW()),
      reviewedAt: isoDaysFromToday(-40, NOW()),
      expired: true,
    }),
  ];

  const heldFrom = isoDaysFromToday(-3, NOW());
  const releasedFrom = isoDaysFromToday(-20, NOW());
  const paidFrom = isoDaysFromToday(-35, NOW());

  const earnings: Earning[] = [
    earning({
      id: "earn-approve-northwind",
      scoutUserId,
      submissionId: "sub-northwind",
      type: "approval",
      amountCents: 150,
      currency: CURRENCY,
      status: "paid",
      holdUntil: addDays(paidFrom, HOLD_DAYS),
      createdAt: paidFrom,
      releasedAt: addDays(paidFrom, HOLD_DAYS),
      paidAt: isoDaysFromToday(-18, NOW()),
      description: "Approval credit · Staff Platform Engineer at Northwind",
    }),
    earning({
      id: "earn-hire-northwind",
      scoutUserId,
      submissionId: "sub-northwind",
      type: "hire",
      amountCents: 10000,
      currency: CURRENCY,
      status: "held",
      holdUntil: addDays(heldFrom, HOLD_DAYS),
      createdAt: heldFrom,
      releasedAt: null,
      paidAt: null,
      description: "Confirmed hire · Staff Platform Engineer at Northwind",
    }),
    earning({
      id: "earn-int-northwind",
      scoutUserId,
      submissionId: "sub-northwind",
      type: "interview",
      amountCents: 1500,
      currency: CURRENCY,
      status: "released",
      holdUntil: addDays(releasedFrom, HOLD_DAYS),
      createdAt: releasedFrom,
      releasedAt: isoDaysFromToday(-5, NOW()),
      paidAt: null,
      description: "Settled interview · Staff Platform Engineer at Northwind",
    }),
    earning({
      id: "earn-int-fieldnote",
      scoutUserId,
      submissionId: "sub-fieldnote",
      type: "interview",
      amountCents: 750,
      currency: CURRENCY,
      status: "held",
      holdUntil: addDays(isoDaysFromToday(-2, NOW()), HOLD_DAYS),
      createdAt: isoDaysFromToday(-2, NOW()),
      releasedAt: null,
      paidAt: null,
      description: "Settled interview · Product Designer at Fieldnote",
    }),
    earning({
      id: "earn-conversion",
      scoutUserId,
      submissionId: "sub-northwind",
      type: "conversion",
      amountCents: 2700,
      currency: CURRENCY,
      status: "released",
      holdUntil: isoDaysFromToday(-1, NOW()),
      createdAt: isoDaysFromToday(-16, NOW()),
      releasedAt: isoDaysFromToday(-1, NOW()),
      paidAt: null,
      description: "10% of Northwind interview fees after they claimed their page",
    }),
  ];

  const notifications: ScoutNotification[] = [
    {
      id: "note-hire",
      scoutUserId,
      title: "Hire confirmed on Northwind",
      description: "$100 is held for 14 days.",
      href: "/submissions/sub-northwind",
      unread: true,
      tone: "success",
      createdAt: heldFrom,
    },
    {
      id: "note-review",
      scoutUserId,
      title: "Harbor Support Lead needs review",
      description: "A moderator has to confirm the career domain.",
      href: "/submissions/sub-harbor",
      unread: true,
      tone: "warning",
      createdAt: isoDaysFromToday(-1, NOW()),
    },
    {
      id: "note-payout",
      scoutUserId,
      title: "Payout sent",
      description: "$18 arrived in your Stripe account.",
      href: "/payouts",
      unread: false,
      tone: "accent",
      createdAt: isoDaysFromToday(-18, NOW()),
    },
  ];

  const payouts: Payout[] = [
    {
      id: "payout-1",
      scoutUserId,
      amountCents: 1800,
      currency: CURRENCY,
      status: "paid",
      requestedAt: isoDaysFromToday(-20, NOW()),
      paidAt: isoDaysFromToday(-18, NOW()),
    },
  ];

  return {
    users: [demoAccount()],
    activeUserId: null,
    submissions,
    earnings,
    notifications,
    payouts,
  };
}
